### ISSUE TITLE
Tasklist check list 

### ISSUE THREAD

**Issue by aramovic79** [aramovic79/VDM2ODM#4]
```[tasklist]
### This is a list of tasks to be done

- [ ] #1 Some additional information available here
- [ ] #2 Some additional information available here
- [ ] #3 Some additional information available here
```
